### ISSUE TITLE
Changes have not propagated to sense keys

### ISSUE THREAD

**Issue by 1313ou** [jmccrae/gwn-scala-api#12]
Changes in XML have not propagated to sense keys:

```
[E] wn-sense-read-sense>index.sense:175553 line=[william_patterson%1:18:00:: 11262565 2 0] exception=[NoSuchElementException] message=[william patterson]
[E] wn-sense-read-sense>index.sense:198247 line=[john_mccormick%1:18:00:: 11205012 2 0] exception=[NoSuchElementException] message=[john mccormick]

```
john mccormick -> john mccormack
william patterson -> william paterson

**Comment by jmccrae** [comment]
This is not a bug, at least not in this project. The sense key should be given as the `dc:identifier` and we use this regardless of whether it matches the lemma. The question of whether English WordNet should be updating the sense keys is much more difficult however

**Comment by 1313ou** [comment]
It's questionable.
Goes against the definition of a sensekey as the concatenation of a lemma and a lex_sense in https://wordnet.princeton.edu/documentation/senseidx5wn. And even the definition of sense as a pair
**sense = (lemma,synset)**
The synset can be accessed (your sensekey may be used as a regular key to synset data), but the information as to which word in the synset members we are talking about is lost (william_patterson is not to be found). So _sensekey_ is a misnomer,  it's a **synsetkey**, not a **sensekey**.

(The issue may be misplaced and should be in the globalwordnet)

**Comment by jmccrae** [comment]
I agree... I will consult with people at GWC this month on issues including this
