### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by goodmami** [jmccrae/gwn-scala-api#20]
This is a request for documentation, specifically adding a CONTRIBUTING.md file or section of the README with instructions for modifying the code.

I was able to clone the code and install sbt (after a few tries with incompatible versions of Java; eventually worked using SDKMan), and then I was able to build and run the code. The problem is how to modify the code. I tried changing part of the XML output for WN-LMF 1.1, and it was able to compile, but it failed the tests. I tried running `gwn` anyway, but I don't see my changes reflected, so maybe the failed tests blocked the jar from being replaced? If that's the case, do I need to update the tests first?

(and, annoyingly, I have to launch a new shell every time sbt runs; see https://github.com/sbt/sbt/issues?q=is%3Aissue+terminal+keystroke)

Any help appreciated!

**Comment by jmccrae** [comment]
Yes, I should so this. I am aware that SBT and some recent versions of Java are not compatible and this is kind of an issue.

Tests do have to pass in order to update `gwn`. You should run the following command to refresh the compiled version:

    sbt assembly

**Comment by jmccrae** [comment]
I added some rough instructions for development. I am happy to say more about how the system works, but perhaps it is best that we just have a 1:1 chat?

**Comment by goodmami** [comment]
Thanks, that's an improvement. And yes, good idea. I'll email about setting that up.
