### ISSUE TITLE
Flawed link count in index file

### ISSUE THREAD

**Issue by 1313ou** [jmccrae/gwn-scala-api#9]
The number of links is (but not always) incorrectly set as in these lines:

[E] wn-index-read-index>index.noun:6535 line=[artificer n 3 **3** @ ~ 3 0 10243745 10003572 09837611  ] exception=[ArrayIndexOutOfBoundsException]
[E] wn-index-read-index>index.noun:6561 line=[artisan n 1 **3** @ ~ 1 0 10003572  ] exception=[ArrayIndexOutOfBoundsException]                                                     
[E] wn-index-read-index>index.noun:6563 line=[artist n 1 **4** + @ ~ 1 0 09841137  ] exception=[ArrayIndexOutOfBoundsException]
etc
where it should be 2,2,3 respectively, where the link pointers are @ ~, @ ~, + @ ~

**Comment by jmccrae** [comment]
This was already fixed before it was reported by this commit https://github.com/jmccrae/gwn-scala-api/commit/c7379b2c651244f29029f18b3b95aef122979871
